import React, { useEffect, useState } from 'react'
import { AlertTriangle, Mail, Power, Settings2, ShieldCheck } from 'lucide-react'
import api from '../../lib/api'
import { AdminNotice, AdminPageHeader, AdminSurface } from '../../components/admin/AdminPrimitives'

type SystemSettings = { registration_enabled: boolean; checkin_enabled: boolean; email_enabled: boolean; maintenance_mode: boolean }
type SettingItem = { key: keyof SystemSettings; group: string; label: string; description: string; icon: typeof Settings2; danger?: boolean }
const settingItems: SettingItem[] = [
  { key: 'registration_enabled', group: 'Registration', label: 'Registration availability', description: 'Allow new student submissions to enter the review queue.', icon: Settings2 },
  { key: 'checkin_enabled', group: 'Check-in', label: 'Entry verification', description: 'Allow approved attendees to be checked in during event operations.', icon: ShieldCheck },
  { key: 'email_enabled', group: 'Communication', label: 'Email delivery', description: 'Allow confirmation and approval messages to be sent.', icon: Mail },
  { key: 'maintenance_mode', group: 'Maintenance', label: 'Maintenance mode', description: 'Temporarily place the public application behind a maintenance screen.', icon: Power, danger: true },
]

export default function AdminSettingsPage() {
  const [settings, setSettings] = useState<SystemSettings | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState<keyof SystemSettings | null>(null); const [error, setError] = useState(''); const [message, setMessage] = useState('')
  const load = async () => { setLoading(true); setError(''); try { const response = await api.get<SystemSettings>('/admin/settings'); setSettings(response.data) } catch (err: any) { setError(err?.response?.data?.detail || err?.message || 'Unable to load system settings.') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  const toggle = async (key: keyof SystemSettings) => { if (!settings || saving) return; setSaving(key); setError(''); setMessage(''); try { const response = await api.patch<SystemSettings>('/admin/settings', { [key]: !settings[key] }); setSettings(response.data); setMessage(`${settingItems.find((item) => item.key === key)?.label} updated.`) } catch (err: any) { setError(err?.response?.data?.detail || err?.message || 'Unable to update setting.') } finally { setSaving(null) } }
  return <div className="space-y-7"><AdminPageHeader eyebrow="System / Control center" title="Pragyarambh system settings" description="Control live event operations from one place." />{error ? <AdminNotice>{error}</AdminNotice> : null}{message ? <AdminNotice tone="success">{message}</AdminNotice> : null}{loading ? <AdminSurface><div className="admin-empty">Loading system controls...</div></AdminSurface> : settings ? <div className="grid gap-5 lg:grid-cols-2">{settingItems.map((item) => { const Icon = item.icon; const enabled = settings[item.key]; return <AdminSurface key={item.key} className={item.danger ? '!border-[#e9bb72]/45' : ''}><div className="flex items-start gap-4"><div className={`admin-stat-icon ${item.danger ? '!text-[#e9bb72]' : ''}`}><Icon size={18} /></div><div className="min-w-0 flex-1"><p className="admin-eyebrow">{item.group}</p><div className="mt-1 flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold text-[#f4eadb]">{item.label}</h2><span className={`admin-badge ${enabled ? 'admin-badge-success' : 'admin-badge-danger'}`}>{enabled ? 'Enabled' : 'Disabled'}</span></div><p className="mt-3 text-sm leading-6 text-[#b9a891]">{item.description}</p>{item.danger ? <p className="mt-4 flex items-center gap-2 text-xs text-[#e9bb72]"><AlertTriangle size={13} /> High-impact public availability control.</p> : null}</div></div><div className="admin-divider my-5" /><div className="flex items-center justify-between gap-4"><span className="text-xs uppercase tracking-[.12em] text-[#8e7963]">Currently {enabled ? 'enabled' : 'disabled'}</span><button role="switch" aria-checked={enabled} aria-label={`Toggle ${item.label}`} className={`admin-toggle ${enabled ? 'is-on' : ''}`} onClick={() => void toggle(item.key)} disabled={saving !== null}><span className="admin-toggle-thumb" />{saving === item.key ? <span className="sr-only">Saving</span> : null}</button></div></AdminSurface>})}</div> : <button className="admin-button admin-button-secondary" onClick={() => void load()}>Try again</button>}</div>
}
