import React, { useEffect, useState } from 'react'
import { ArrowUpRight, Camera, CheckCircle2, Clock3, RefreshCw, ShieldCheck, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import api from '../../lib/api'
import { AdminNotice, AdminPageHeader, AdminSectionHeading, AdminSurface } from '../../components/admin/AdminPrimitives'

type CheckinStats = { event_title: string | null; total_checked_in: number; male_checked_in: number; female_checked_in: number; other_checked_in: number; approved_eligible: number; remaining_to_check_in: number }
const empty: CheckinStats = { event_title: null, total_checked_in: 0, male_checked_in: 0, female_checked_in: 0, other_checked_in: 0, approved_eligible: 0, remaining_to_check_in: 0 }

export default function AdminCheckinOverviewPage() {
  const [stats, setStats] = useState(empty)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const load = async () => { setLoading(true); setError(''); try { const response = await api.get<CheckinStats>('/security/dashboard'); setStats(response.data) } catch (err: any) { setError(err?.response?.data?.detail || err?.message || 'Unable to load check-in operations.') } finally { setLoading(false) } }
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 15000); return () => window.clearInterval(timer) }, [])
  const progress = stats.approved_eligible ? Math.min(100, (stats.total_checked_in / stats.approved_eligible) * 100) : 0
  const genderRows = [{ label: 'Male', count: stats.male_checked_in, Icon: Users }, { label: 'Female', count: stats.female_checked_in, Icon: Users }, { label: 'Other', count: stats.other_checked_in, Icon: Users }]
  return <div className="space-y-7"><AdminPageHeader eyebrow="Operations / Check-in" title="Check-in overview" description={`${stats.event_title || 'Pragyarambh 2026'} · Live attendance intelligence for event-day operations.`} action={<button className="admin-button admin-button-secondary" onClick={() => void load()} disabled={loading}><RefreshCw size={15} className={loading ? 'animate-spin' : ''} /> Refresh</button>} />{error ? <AdminNotice>{error}</AdminNotice> : null}<section className="grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><AdminSurface className="flex min-h-[220px] flex-col justify-between !border-[#d3a654]/35"><div><p className="admin-eyebrow">Total checked in</p><p className="mt-5 font-[Space_Grotesk] text-7xl font-bold tracking-[-.08em] text-[#f4eadb] sm:text-8xl">{loading ? '—' : stats.total_checked_in.toLocaleString()}</p></div><div><div className="flex justify-between text-xs text-[#b9a891]"><span>{stats.approved_eligible.toLocaleString()} approved eligible</span><span>{stats.remaining_to_check_in.toLocaleString()} remaining</span></div><div className="mt-3 h-2 bg-[#160e0a]"><div className="h-full bg-[#d3a654] transition-all" style={{ width: `${progress}%` }} /></div></div></AdminSurface><AdminSurface><AdminSectionHeading eyebrow="Live balance" title="Attendance ratio" /><div className="grid grid-cols-2 gap-3"><div className="border border-[#d3a654]/15 p-4"><p className="text-xs text-[#a9957d]">Approved</p><p className="mt-2 text-3xl font-bold text-[#f4eadb]">{stats.approved_eligible}</p></div><div className="border border-[#d3a654]/15 p-4"><p className="text-xs text-[#a9957d]">Remaining</p><p className="mt-2 text-3xl font-bold text-[#e9bb72]">{stats.remaining_to_check_in}</p></div></div></AdminSurface></section><AdminSurface><AdminSectionHeading eyebrow="Attendee profile" title="Gender breakdown" /><div className="grid gap-3 sm:grid-cols-3">{genderRows.map(({ label, count, Icon }) => <div key={label} className="flex items-center justify-between border-b border-[#d3a654]/15 px-1 py-4"><div className="flex items-center gap-3"><span className="admin-stat-icon"><Icon size={15} /></span><span className="text-sm text-[#b9a891]">{label}</span></div><strong className="text-2xl text-[#f4eadb]">{count.toLocaleString()}</strong></div>)}</div></AdminSurface><AdminSurface><AdminSectionHeading eyebrow="Security team" title="Event-day access" /><div className="grid gap-3 sm:grid-cols-3"><Link className="admin-button admin-button-secondary justify-between" to="/admin/security-volunteers">Security volunteers <ShieldCheck size={15} /></Link><Link className="admin-button admin-button-primary justify-between" to="/security/scanner">Open scanner <Camera size={15} /></Link><Link className="admin-button admin-button-secondary justify-between" to="/admin/registrations?checked_in=false">Review remaining <ArrowUpRight size={15} /></Link></div></AdminSurface></div>
}
